M48
; DRILL file {KiCad (6.0.9)} date Mon Nov 21 22:50:26 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-21T22:50:26+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X3.9488Y-3.7264
X4.122Y-3.7264
T2
X0.9843Y-0.9843
X0.9843Y-3.7402
X4.5276Y-3.7402
X4.5433Y-0.9843
T0
M30
