name: Auto-Push schematic PDF to Repo

on:
  push:
    branches:
      - main  # Adjust the branch name as needed
jobs:
  Generate_kicad_files:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[AUTO]')"
    steps:
      - uses: actions/checkout@v3
      - name: Check for Schematics Modification
        id: changed-files-specific
        uses: tj-actions/changed-files@v39
        with:
          files: Elekit2.0.kicad_sch
      - name: Setup Kicad
        if: steps.changed-files-specific.outputs.any_changed == 'true' || "!contains(github.event.head_commit.message, '[FORCE]')"
        uses: actions-for-kicad/setup-kicad@v1.0
        with:
          version: '7.0'
      - name: Generate files
        if: steps.changed-files-specific.outputs.any_changed == 'true' || "!contains(github.event.head_commit.message, '[FORCE]')"
        uses: actions-for-kicad/generate-kicad-files@v1.0
        with:
          file: './Elekit2.0.kicad_sch'
          type: 'schematic_pdf'
      - name: Rename Artifacts
        if: steps.changed-files-specific.outputs.any_changed == 'true' || "!contains(github.event.head_commit.message, '[FORCE]')"
        run: |
          rm -f output/schematic.pdf
          mkdir -p output/
          mv ./Elekit2.0.pdf output/schematic.pdf
      - name: Commit and Push PDF
        if: (steps.changed-files-specific.outputs.any_changed == 'true' || "!contains(github.event.head_commit.message, '[FORCE]')") && steps.auto_tag_check.outcome != 'success' && steps.schematics_check.outcome != 'success'
        run: |
          # Commit the new PDF file
          git config user.name "Actions"
          git config user.email "youremail@example.com"
          git add output/schematic.pdf
          git commit -m "Update PDFs [AUTO]"
          git tag -a "v$(date +'%Y%m%d%H%M%S')" -m "Autogenerated tag"
          git push origin main --follow-tags
