on: push
name: Generate kicad files
jobs:
  Generate_kicad_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-for-kicad/setup-kicad@v1.0
        with:
          version: '7.0'
      - uses: actions-for-kicad/generate-kicad-files@v1.0
        with:
          file: './Elekit2.0.kicad_sch'
          type: 'schematic_pdf'
      - name: Rename Artifacts
        run: |
          mv ./Elekit2.0.kicad_sch ./schematic.pdf
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
              output/schematic.pdf
      - name: Get Release URL
        id: release_url
        run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt
      - name: Publish Release URL
        run: echo "::set-output name=RELEASE_URL::${{ steps.release_url.outputs.RELEASE_URL }}"

  Publish_Release_URL:
    needs: Generate_kicad_files
    runs-on: ubuntu-latest
    steps:
      - name: Publish Release URL
        run: |
          echo "Release URL: ${{ needs.Generate_kicad_files.outputs.RELEASE_URL }}"
